name: testing-terraform-in-github-actions

on:
  push:
    branches:
      - main

jobs:
  deploy-to-pk1:
    environment: pk1
    concurrency: pk1
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialise
        id: init
        run: |
          terraform init -upgrade -backend-config="key=${{ vars.ENV }}/terraform.tfstate" -backend-config="dynamodb_table=core-tf-lock-dynamo-pk-test-${{ vars.ENV }}"

      - name: Validation
        id: validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_snd_bucket_name: ${{ vars.SND_BUCKET_NAME }}
          TF_VAR_third_bucket_name: ${{ secrets.THIRD_BUCKET_NAME }}
          TF_VAR_env: ${{ vars.ENV }}
        #   TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
        #   TF_VAR_jwtSecret: ${{ secrets.JWT_SECRET }}

  deploy-to-pk2:
    needs: deploy-to-pk1
    if: ${{ needs.deploy-to-pk1.result == 'success' }}
    environment: pk2
    concurrency: pk2
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialise
        id: init
        run: |
          terraform fmt
          terraform init -upgrade

      - name: Validation
        id: validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_snd_bucket_name: ${{ vars.SND_BUCKET_NAME }}
          TF_VAR_third_bucket_name: ${{ secrets.THIRD_BUCKET_NAME }}
          TF_VAR_env: ${{ vars.ENV }}
        #   TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
        #   TF_VAR_jwtSecret: ${{ secrets.JWT_SECRET }}
